volumes:
  kafka_data:

services:
  front-ui-service:
    build:
      context: ./front-ui
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  accounts-service:
    build:
      context: ./accounts
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - bank-db

  bank-db:
    image: postgres:16
    container_name: bank-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: "bank-db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"

  blocker-service:
    build:
      context: ./blocker
      dockerfile: Dockerfile
    ports:
      - "8082:8082"

  cash-service:
    build:
      context: ./cash
      dockerfile: Dockerfile
    ports:
      - "8083:8083"

  exchange-service:
    build:
      context: ./exchange
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    depends_on:
      - exchange-db

  exchange-db:
    image: postgres:16
    container_name: exchange-db
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: "exchange-db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"

  exchange-generator-service:
    build:
      context: ./exchange-generator
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
    depends_on:
      - exchange-service

  notifications-service:
    build:
      context: ./notifications
      dockerfile: Dockerfile
    ports:
      - "8086:8086"

  transfer-service:
    build:
      context: ./transfer
      dockerfile: Dockerfile
    ports:
      - "8087:8087"

  kafka:
    image: apache/kafka:4.0.0
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_KRAFT_CLUSTER_ID=abcdef1234567890
      - ALLOW_PLAINTEXT_LISTENER=yes

    volumes:
      - kafka_data:/bitnami/kafka

  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - monitoring-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    networks:
      - elastic-network

  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.0
    container_name: kibana
    ports:
      - "5601:5601"
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - elastic-network

networks:
  monitoring-network:
    driver: bridge
  elastic-network:
    driver: bridge