apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "blocker.fullname" . }}
  labels:
    {{- include "blocker.labels" . | nindent 4 }}
data:
    {{- range $key, $value := .Values.config }}
    {{- if ne $key "database_url" }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
    {{- end }}

    KAFKA_BOOTSTRAP_SERVERS: {{ .Values.config.kafka.bootstrapServers | quote }}