global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'accounts'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: ['accounts:8081']
        labels:
          application: 'accounts'
  - job_name: 'blocker'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: ['blocker:8082']
        labels:
          application: 'blocker'
  - job_name: 'cash'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: ['cash:8083']
        labels:
          application: 'cash'
  - job_name: 'exchange'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: ['exchange:8084']
        labels:
          application: 'exchange'
  - job_name: 'exchange-generator'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: ['exchange-generator:8085']
        labels:
          application: 'exchange-generator'
  - job_name: 'front-ui'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: ['front-ui:8080']
        labels:
          application: 'front-ui'
  - job_name: 'notifications'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: ['notifications:8086']
        labels:
          application: 'notifications'
  - job_name: 'transfer'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: ['transfer:8087']
        labels:
          application: 'transfer'