server:
  port: 8081

spring:
  application:
    name: accounts
  datasource:
    url: jdbc:postgresql://localhost:5432/bank
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer 
      buffer-memory: 125829120
      client-id: "accounts"
      acks: 0
      batch-size: 1
      retries: 0
      properties:
        linger.ms: 1
        max.request.size: 125829120
    properties:
      buffer.memory: 125829120
      linger.ms: 1
      max.partition.fetch.bytes: 125829120
      max.request.size: 125829120
      session.timeout.ms: 60000
      enable.idempotence: false

hibernate:
  dialect: org.hibernate.dialect.PostgreSQLDialect
  show_sql: true

kafka-topics:
  out:
    - notifications


management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  endpoint:
    health:
      show-details: always
  zipkin:
    tracing:
      endpoint: localhost:9411
  tracing:
    sampling:
      probability: 1
  metrics:
    distribution:
      percentiles[http.server.requests]: 0.5, 0.90, 0.95, 0.99
      percentiles-histogram[http.server.requests]: true
      slo[http.server.requests]: 100ms, 250ms, 500ms, 1s, 2s, 5s, 10s, 30s
