server:
  port: 8081

spring:
#  profiles:
#    active: dev
  application:
    name: accounts

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    producer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer 
      buffer-memory: 125829120
      client-id: ${KAFKA_CLIENT_ID}
      acks: 0
      batch-size: 1
      retries: 0
      properties:
        linger.ms: 1
        max.request.size: 125829120
    properties:
      buffer.memory: 125829120
      linger.ms: 1
      max.partition.fetch.bytes: 125829120
      max.request.size: 125829120
      session.timeout.ms: 60000
      enable.idempotence: false

hibernate:
  dialect: org.hibernate.dialect.PostgreSQLDialect
  show_sql: true

kafka-topics:
  out:
    - ${KAFKA_TOPIC_OUT_NOTIFICATIONS}

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always