server:
  port: 8080
  servlet:
    encoding:
      enabled: false
      charset: UTF-8
      force: true

spring:
  application:
    name: front-ui

client:
  accounts:
    base-url: http://localhost:8081/accounts
    connect-timeout-ms: 1000
    response-timeout-ms: 1000
  cash:
    base-url: http://localhost:8083/cash
    connect-timeout-ms: 1000
    response-timeout-ms: 1000
  transfer:
    base-url: http://localhost:8087/transfer
    connect-timeout-ms: 1000
    response-timeout-ms: 1000
  exchange:
    base-url: http://localhost:8084/rates
    connect-timeout-ms: 1000
    response-timeout-ms: 1000

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  endpoint:
    health:
      show-details: always
  zipkin:
    tracing:
      endpoint: localhost:9411
  tracing:
    sampling:
      probability: 1
  metrics:
    distribution:
      percentiles[http.server.requests]: 0.5, 0.90, 0.95, 0.99
      percentiles-histogram[http.server.requests]: true
      slo[http.server.requests]: 100ms, 250ms, 500ms, 1s, 2s, 5s, 10s, 30s
