server:
  port: 8080
  servlet:
    encoding:
      enabled: false
      charset: UTF-8
      force: true

spring:
  application:
    name: front-ui

client:
  accounts:
    base-url: http://localhost:8081/accounts
    connect-timeout-ms: 1000
    response-timeout-ms: 1000
  cash:
    base-url: http://localhost:8083/cash
    connect-timeout-ms: 1000
    response-timeout-ms: 1000
  transfer:
    base-url: http://localhost:8087/transfer
    connect-timeout-ms: 1000
    response-timeout-ms: 1000
  exchange:
    base-url: http://localhost:8084/rates
    connect-timeout-ms: 1000
    response-timeout-ms: 1000

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always
  zipkin:
    tracing:
      endpoint: localhost:9411
  tracing:
    sampling:
      probability: 1
