server:
  port: 8085

spring:
  application:
    name: exchange-generator
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer 
      buffer-memory: 125829120
      client-id: "exchange-generator"
      acks: 0
      batch-size: 1
      retries: 0
      properties:
        linger.ms: 1
        max.request.size: 125829120
    properties:
      buffer.memory: 125829120
      linger.ms: 1
      max.partition.fetch.bytes: 125829120
      max.request.size: 125829120
      session.timeout.ms: 60000
      enable.idempotence: false

kafka-topics:
  out:
    - rate

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always
  zipkin:
    tracing:
      endpoint: localhost:9411
  tracing:
    sampling:
      probability: 1