server:
  port: 8086

spring:
#  profiles:
#    active: dev
  application:
    name: notifications
  kafka:
    consumer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
      group-id: ${KAFKA_GROUP_ID}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: latest
      enable-auto-commit: true
      auto-commit-interval: 5000
      max-poll-records: 10
    listener:
      client-id: ${KAFKA_CLIENT_ID}
      ack-mode: manual_immediate
      async-acks: false
      auto-startup: true
      concurrency: 1
      immediate-stop: true
      missing-topics-fatal: true
      type: single
    properties:
      buffer.memory: 125829120
      linger.ms: 1
      max.partition.fetch.bytes: 125829120
      max.request.size: 125829120
      session.timeout.ms: 60000

kafka-topics:
  in:
    - ${KAFKA_TOPIC_IN_NOTIFICATIONS}

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  endpoint:
    health:
      show-details: always
  zipkin:
    tracing:
      endpoint: ${MANAGEMENT_ZIPKIN_TRACING_ENDPOINT}
  tracing:
    sampling:
      probability: 1
  metrics:
    distribution:
      percentiles[http.server.requests]: 0.5, 0.90, 0.95, 0.99
      percentiles-histogram[http.server.requests]: true
      slo[http.server.requests]: 100ms, 250ms, 500ms, 1s, 2s, 5s, 10s, 30s