server:
  port: 8084

spring:
#  profiles:
#    active: dev
  application:
    name: exchange
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    consumer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
      group-id: ${KAFKA_GROUP_ID}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: latest
      enable-auto-commit: true
      auto-commit-interval: 5000
      max-poll-records: 10
    listener:
      client-id: ${KAFKA_CLIENT_ID}
      ack-mode: manual_immediate
      async-acks: false
      auto-startup: true
      concurrency: 1
      immediate-stop: true
      missing-topics-fatal: true
      type: single
    properties:
      buffer.memory: 125829120
      linger.ms: 1
      max.partition.fetch.bytes: 125829120
      max.request.size: 125829120
      session.timeout.ms: 60000

kafka-topics:
  in:
    - ${KAFKA_TOPIC_IN_RATE}

hibernate:
  dialect: org.hibernate.dialect.PostgreSQLDialect
  show_sql: true

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always
  zipkin:
    tracing:
      endpoint: ${MANAGEMENT_ZIPKIN_TRACING_ENDPOINT}
  tracing:
    sampling:
      probability: 1